### ISSUE TITLE
Deployment for kubeadm clusters no longer works with 1.6

### ISSUE THREAD

**Issue by mortensteenrasmussen** [romana/romana#161]
In `containerize/specs/romana-kubeadm.yml`, you run the `romama-services` daemonset under this nodeselector:
```
      nodeSelector:
        kubeadm.alpha.kubernetes.io/role: master
```

In a kubeadm 1.6 cluster, the master node now looks like this, which means the `romana-services` pod will never be scheduled.

```
apiVersion: v1
kind: Node
metadata:
  annotations:
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    kubernetes.io/hostname: kube-nt-1
    node-role.kubernetes.io/master: ""
```

```
sysadm@kube-nt-1:~$ kubectl get ds --all-namespaces
NAMESPACE     NAME              DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE-SELECTOR                             AGE
kube-system   kube-proxy        3         3         3         3            3           <none>                                    26m
kube-system   romana-agent      2         2         2         2            2           <none>                                    17s
kube-system   romana-services   0         0         0         0            0           kubeadm.alpha.kubernetes.io/role=master   18s
```

I added the label to my master to get it running, but the YAML file should be updated to use the correct nodeSelector and/or toleration.

**Comment by mortensteenrasmussen** [comment]
I changed the following to get it working:
From:
```
      nodeSelector:
        kubeadm.alpha.kubernetes.io/role: master
```

to:
```
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      nodeSelector:
        node-role.kubernetes.io/master: ""
```
