### ISSUE TITLE
Consider using async for long tasks (eg: devstack installation stage)

### ISSUE THREAD

**Issue by cgilmour** [romana/romana#22]
For one task in particular, there can be around 15 minutes without any activity.
This can cause SSH to time out or drop without being noticed by the Ansible client side.

A suggestion for this is to change it to an async task with approximate timeout values.
Eg:

``` yaml
 - name: Run devstack "stack" script
   shell: chdir="~/devstack" creates="~/devstack/stack.sh.log" ./stack.sh
   async: 3600
```

It could also use a longer poll interval than the default 10s, to reduce the amount of on-screen noise while it's checking for completion.
